# Generated by Django 2.2.12 on 2022-01-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='fox',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
